const val LAUNCH_APP = "launch_app"
const val GET_INSTALLED_APPS = "get_installed_apps"
const val CAN_LAUNCH_APP = "can_launch_app"
const val APP_IDENTIFIER= "appIdentifier"
const val STORE_URL = "storeUrl"
const val LAUNCH_STORE = "launchStore"
const val DATA = "data"

const val ERROR_NOT_FOUND = "404"
const val DEFAULT_ERROR = "100"